version: 0.2

phases:
  pre_build:
    commands:
      - chmod +x gradlew
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew build -x test
artifacts:
  files:
    - build/libs/onmyoji-bot-0.0.1-SNAPSHOT.war
